name: Action Sample

on:
  push:
    branches:
      - master
  workflow_dispatch:

job:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: execute echo command
        run: echo "Hello world!"
      - name: execute echo command 2
        run: echo "Hello world!2"
