name: Action Sample

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: execute echo command
        run: echo "Hello world!"
      - name: execute echo command 2
        run: echo "Hello world!2"
      - name: read sample.txt
        run: cat ../../sample.txt
